---
server:
  port: 3000

routers:
  enabled: true

react:
  application:
    languages:
      - en
    defaultLanguage: 'en'
    site:
      title: 'Site Title'
      logo: '/images/logo.svg'
      provider: 'Site Company, Ltd.'
