---
server:
  port: 3000

routers:
  enabled: true

renderers:
  html:
    module: 'express-es6-template-engine'
    path: 'views'

react:
  application:
    languages:
      - en
    defaultLanguage: 'en'
    site:
      title: 'Site Title'
      logo: '/images/logo.svg'
      provider: 'Site Company, Ltd.'

bodyparser:
  enabled: true

services:
  cache:
    enabled: true
    engine: 'memcache'

session:
  enabled: true
  secret: 'session secret'
