# Default environment, refs ./clients/gui
target:
  client: 'dist'

nodemon:
  watch:
    - 'client/*.js'
    - 'client/**/*.js'
    - 'config/*.yml'
    - 'lib/*.js'
    - 'lib/**/*.js'
    - 'routers/*.js'
    - 'routers/**/*.js'
    - 'server/*.js'
    - 'server/**/*.js'
    - 'services/*.js'
    - 'services/**/*.js'

sass:
  module: 'sass'
  lint: false