---
react:
  enabled: true
  entry: 'test'

  application:
    languages:
      - en
      - fi
    defaultLanguage: 'fi'


  stylesheets:
    - '/css/test.min.css'

services:
  events:
    enabled: true

  l10n:
    enabled: true

  mailer:
    smtp:
      server:
        host: 'localhost'
        port: 4001

  cache:
    engine: 'memcache'
    enabled: false

  database:
    engine: 'psql'
    connection:
      database: 'reactserver'
      username: 'reactserver'
      password: 'reactserver'