---
react:
  enabled: true
  entry: 'test'

  application:
    languages:
      - en
      - fi
    defaultLanguage: 'fi'


  stylesheets:
    - '/css/test.min.css'

services:
  l10n:
    enabled: true
